# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            JMPergar
tagline:          'Android Tech Lead'
description:      'Android Tech Lead at jobandtalent and GDG Madrid Organizer. AndroCode Blog Founder. Beer Lover and Andalú.'
url:              http://jmpergar.com
baseurl:          /

author:
  name:           'José Manuel Pereira García'
  url:            https://twitter.com/JMPergar

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/jmpergar/jmpergar.github.io

# Social Media Content
twitter_username: jmpergar
github_username:  jmpergar
googleplus_username: +JoseMPereira
linkedin_username: jmpergar
