# Site settings
title: JMPergar
email: jm.pereira.g@gmail.com
url: https://jmpergar.github.io
description: "La suerte no se compila sola"
skills: "Android Team Lead at <a href="https://twitter.com/jobandtalentEng">@JobAndTalentEng</a> and @GDGMadrid Organizer. Founder of @AndroCode. Formerly @RedboothHQ and @GDGBarcelona. Beer Lover and Andalú."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: a3ca39 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: José Manuel Pereira García
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jmpergar
 # - title: facebook
 #  url:
  - title: stack-overflow
    url: http://stackoverflow.com/users/1187421/jmpergar
 # - title: bitbucket
 #  url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jmpergar
  - title: google-plus
    url: https://plus.google.com/+JoséMPereira/
  - title: linkedin
    url: https://es.linkedin.com/in/jmpergar
  - title: instagram
    url: https://instagram.com/jmpergar/

# Postal address (add as many lines as necessary)
address:
  - line: Somewhere
  - line: at the world

# Credits content
credits: 'Mmmmm ola ke ase!'

# Build settings
markdown: kramdown
permalink: pretty
